In [44]:
#### Import NumPy as np
import numpy as np

In [45]:
#### Create an array of 10 zeros
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
#### Create an array of 10 ones
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [47]:
#### Create an array of 10 fives
arr = np.ones(10)*5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [48]:
#### Create an array of the integers from 10 to 50
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [49]:
#### Create an array of all the even integers from 10 to 50
arr = np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [50]:
#### Create a 3x3 matrix with values ranging from 0 to 8
arr = np.arange(0,9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
#### Create a 3x3 identity matrix
arr = np.eye(3,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
#### Use NumPy to generate a random number between 0 and 1
rand_number = np.random.rand(1)
rand_number

array([0.68415704])

In [53]:
#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
arr = np.random.normal(0,1,25)
arr

array([ 0.03721209,  0.51000492, -0.96610904, -1.02085343, -1.93954011,
       -0.44454725,  0.9109176 , -1.23812612, -0.54352914, -0.13448305,
       -1.47462559, -0.74176592,  0.74455328, -0.04521573, -0.29181718,
       -0.23500008,  0.77191748, -0.40522442,  0.00435351, -0.17321936,
       -0.82265826,  0.79457839, -0.29388625,  1.37931976, -2.05253713])

In [67]:
#### Create the following matrix:
arr = np.arange(1,101).reshape(10,10) / 10
arr

array([[ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ],
       [ 1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ],
       [ 2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ],
       [ 3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ],
       [ 4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ],
       [ 5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ],
       [ 6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ],
       [ 7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ],
       [ 8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ],
       [ 9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. ]])

In [56]:
#### Create an array of 20 linearly spaced points between 0 and 1:
arr = np.linspace(0,1,20)
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [68]:
## Numpy Indexing and Selection
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [73]:
## 1 selection
mat[2:,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [74]:
# 2 selection
mat[3,4]

20

In [82]:
mat[:3,[1]]

array([[ 2],
       [ 7],
       [12]])

In [83]:
mat[4,]

array([21, 22, 23, 24, 25])

In [90]:
mat[3:5,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [91]:
# get the sum of array
np.sum(mat)

325

In [92]:
# get the standard deviation of array
np.std(mat)

7.211102550927978

In [95]:
#### Get the sum of all the columns in mat
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])