# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.


* 1) Indexing
    - 1.1) Indexing 1D array (Vectors)
    - 1.2) Indexing 2D array (Matrices)
    - 1.3) Fancy Indexing

In [1]:
import numpy as np

In [4]:
arr_1 = np.arange(10, 40, 2)
arr_1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [5]:
arr_1.shape

(15,)

In [6]:
arr_1[0]

10

In [7]:
arr_1[5]

20

In [8]:
arr_1[-1]

38

## 1) Indexing
The simplest way to pick one or some elements of an array looks very similar to python lists:

### 1.1) Indexing a 1D array (Vectors)

In [14]:
arr_2 = np.random.randint(0, 100, (5, 6))
arr_2

array([[52, 90, 57, 70,  8, 70],
       [57, 87, 36, 21, 48, 13],
       [15, 85, 58, 73,  7, 61],
       [61, 68,  0, 33, 34, 85],
       [18, 47, 96, 29, 71, 81]])

In [15]:
arr_2[0]

array([52, 90, 57, 70,  8, 70])

In [16]:
arr_2[1]

array([57, 87, 36, 21, 48, 13])

In [17]:
arr_2[0:2]

array([[52, 90, 57, 70,  8, 70],
       [57, 87, 36, 21, 48, 13]])

In [18]:
arr_2[[0, 3, 4]]

array([[52, 90, 57, 70,  8, 70],
       [61, 68,  0, 33, 34, 85],
       [18, 47, 96, 29, 71, 81]])

In [19]:
arr_2[:, 2]

array([57, 36, 58,  0, 96])

In [20]:
arr_2[:, [0, 4]]

array([[52,  8],
       [57, 48],
       [15,  7],
       [61, 34],
       [18, 71]])

In [21]:
arr_2[:, 0:2]

array([[52, 90],
       [57, 87],
       [15, 85],
       [61, 68],
       [18, 47]])

In [22]:
arr_2

array([[52, 90, 57, 70,  8, 70],
       [57, 87, 36, 21, 48, 13],
       [15, 85, 58, 73,  7, 61],
       [61, 68,  0, 33, 34, 85],
       [18, 47, 96, 29, 71, 81]])

In [23]:
arr_2[2, 1]

85

In [24]:
arr_2[ 1:3  , 1:4  ]

array([[87, 36, 21],
       [85, 58, 73]])

In [27]:
arr_2

array([[52, 90, 57, 70,  8, 70],
       [57, 87, 36, 21, 48, 13],
       [15, 85, 58, 73,  7, 61],
       [61, 68,  0, 33, 34, 85],
       [18, 47, 96, 29, 71, 81]])

In [36]:
arr_2[[1,3], [1,2]]

array([87,  0])

In [37]:
arr_2[-1]

array([18, 47, 96, 29, 71, 81])

In [38]:
arr_2[: , -1]

array([70, 13, 61, 85, 81])

### 1.2) Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

# Great Job!
