# Series

The first main data type we will learn about for pandas is the Series data type. Let's import Pandas and explore the Series object.

A Series is very similar to a NumPy array (in fact it is built on top of the NumPy array object). What differentiates the NumPy array from a Series, is that a Series can have axis labels, meaning it can be indexed by a label, instead of just a number location. It also doesn't need to hold numeric data, it can hold any arbitrary Python Object.

Let's explore this concept through some examples:

* 1) Creating a Series
* 2) Access Values
* 3) Opeartions

In [1]:
import numpy as np
import pandas as pd

## 1) Creating a Series

You can convert a list,numpy array, or dictionary to a Series:

In [2]:
labels = ['a','b','c']

In [3]:
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [4]:
labels

['a', 'b', 'c']

In [5]:
my_list

[10, 20, 30]

In [6]:
arr

array([10, 20, 30])

In [7]:
d

{'a': 10, 'b': 20, 'c': 30}

**Using Lists**

In [8]:
pd.Series(data = my_list)

0    10
1    20
2    30
dtype: int64

In [9]:
pd.Series(data=my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series(my_list, labels)

a    10
b    20
c    30
dtype: int64

**Using NumPy Arrays**

In [11]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [12]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int32

**Using Dictionary**

In [13]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

## 2) Access Values

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look ups of information (works like a hash table or dictionary).

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [9]:
my_data = [1,2,3,4]
countries = ['USA', 'Germany','Egypt', 'Japan']
ser1 = pd.Series(my_data, countries)                                   

In [10]:
ser1

USA        1
Germany    2
Egypt      3
Japan      4
dtype: int64

In [15]:
ser1['USA']

1

In [16]:
ser1['Egypt']

3

## 3) Operations

In [11]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
new = arr1 + arr1
new

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
new.min()

0

In [14]:
new.max()

18

In [15]:
new.sum()

90

In [16]:
ser1 = pd.Series(arr1)
ser1

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [17]:
ser1 + ser1

0     0
1     2
2     4
3     6
4     8
5    10
6    12
7    14
8    16
9    18
dtype: int32

Let's stop here for now and move on to DataFrames, which will expand on the concept of Series!
# Great Job!