# NumPy Operations


* 1) Arithmetic and Logic
    - 1.1) Arithmetic
    - 1.2) Logic
* 2) Universal Array Functions
    - 2.1) max, min, average, sum
    - 2.2) power, sqrt, exp, log
    - 2.3) sin, cos, tan
    - 2.4) dot product

## 1) Arithmetic and Logic

You can easily perform array with array arithmetic, or scalar with array arithmetic. <br>
You can also perform logic operation on array. <br>

**Broadcasting**: a technique in numpy used to make operations on different array sizes like multiply or sum a scaler to an array.

Let's see some examples:

### 1.1) Arithmetic

In [2]:
import numpy as np

In [3]:
arr_1 = np.random.randint(1,10, (5,5))
arr_1

array([[7, 8, 3, 9, 3],
       [8, 6, 9, 1, 7],
       [1, 9, 5, 9, 8],
       [1, 1, 1, 9, 9],
       [7, 1, 8, 8, 1]])

In [4]:
arr_2 = np.random.randint(10,20, (5,5))
arr_2

array([[10, 10, 10, 16, 12],
       [18, 15, 11, 14, 19],
       [10, 18, 18, 15, 10],
       [13, 13, 11, 14, 16],
       [16, 14, 19, 14, 11]])

In [5]:
arr_1 + arr_2

array([[17, 18, 13, 25, 15],
       [26, 21, 20, 15, 26],
       [11, 27, 23, 24, 18],
       [14, 14, 12, 23, 25],
       [23, 15, 27, 22, 12]])

In [6]:
arr_1 - arr_2

array([[ -3,  -2,  -7,  -7,  -9],
       [-10,  -9,  -2, -13, -12],
       [ -9,  -9, -13,  -6,  -2],
       [-12, -12, -10,  -5,  -7],
       [ -9, -13, -11,  -6, -10]])

In [7]:
arr_1 * arr_2

array([[ 70,  80,  30, 144,  36],
       [144,  90,  99,  14, 133],
       [ 10, 162,  90, 135,  80],
       [ 13,  13,  11, 126, 144],
       [112,  14, 152, 112,  11]])

In [8]:
arr_1 / arr_2

array([[0.7       , 0.8       , 0.3       , 0.5625    , 0.25      ],
       [0.44444444, 0.4       , 0.81818182, 0.07142857, 0.36842105],
       [0.1       , 0.5       , 0.27777778, 0.6       , 0.8       ],
       [0.07692308, 0.07692308, 0.09090909, 0.64285714, 0.5625    ],
       [0.4375    , 0.07142857, 0.42105263, 0.57142857, 0.09090909]])

In [9]:
arr_2[0,0] = 0 
arr_2

array([[ 0, 10, 10, 16, 12],
       [18, 15, 11, 14, 19],
       [10, 18, 18, 15, 10],
       [13, 13, 11, 14, 16],
       [16, 14, 19, 14, 11]])

In [10]:
arr_1 / arr_2

<ipython-input-10-2d52afb29077>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr_1 / arr_2


array([[       inf, 0.8       , 0.3       , 0.5625    , 0.25      ],
       [0.44444444, 0.4       , 0.81818182, 0.07142857, 0.36842105],
       [0.1       , 0.5       , 0.27777778, 0.6       , 0.8       ],
       [0.07692308, 0.07692308, 0.09090909, 0.64285714, 0.5625    ],
       [0.4375    , 0.07142857, 0.42105263, 0.57142857, 0.09090909]])

In [11]:
arr_3 = np.random.randint(1,10, (3,5))
arr_4 = np.random.randint(1,10, (4,5))

In [12]:
arr_3 + arr_4

ValueError: operands could not be broadcast together with shapes (3,5) (4,5) 

In [13]:
arr_3 = np.random.randint(1,10, (1,3))
arr_4 = np.random.randint(1,10, (4,3))
arr_3

array([[7, 3, 2]])

In [14]:
arr_4

array([[3, 2, 5],
       [1, 1, 6],
       [4, 6, 5],
       [2, 9, 7]])

In [15]:
arr_3*arr_4

array([[21,  6, 10],
       [ 7,  3, 12],
       [28, 18, 10],
       [14, 27, 14]])

In [16]:
arr_3 = np.random.randint(1,10, (2,3))
arr_4 = np.random.randint(1,10, (2,6))


In [17]:
arr_3

array([[4, 3, 4],
       [7, 1, 9]])

In [18]:
arr_4

array([[9, 8, 4, 8, 1, 6],
       [3, 8, 5, 1, 6, 3]])

In [19]:
arr_3*arr_4

ValueError: operands could not be broadcast together with shapes (2,3) (2,6) 

### 2.2) Logic

In [3]:
arr_1 = np.random.randint(1,10, (5,5))
arr_1

array([[5, 7, 5, 7, 6],
       [4, 7, 3, 5, 8],
       [6, 3, 2, 4, 1],
       [4, 7, 3, 4, 8],
       [7, 7, 7, 3, 2]])

In [4]:
x = (arr_1 != 5)
x

array([[False,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [5]:
x = arr_1 < 3
x

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False,  True],
       [False, False, False, False, False],
       [False, False, False, False,  True]])

In [10]:
np.sum(x)

3

## 2) Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

### 2.1) max, min, average, sum

**max**

In [6]:
arr_1 = np.random.randint(1,10, (5,5))
arr_1

array([[7, 5, 9, 7, 2],
       [6, 8, 3, 3, 3],
       [5, 5, 3, 8, 7],
       [6, 5, 4, 4, 2],
       [3, 4, 5, 9, 8]])

In [9]:
np.max(arr_1)

9

In [11]:
np.max(arr_1, axis = 1)

array([9, 8, 8, 6, 9])

In [12]:
np.max(arr_1, axis = 0)

array([7, 8, 9, 9, 8])

**min**

In [8]:
np.min(arr_1)

2

**average**

In [24]:
arr_1

array([[4, 3, 2, 5, 4],
       [8, 4, 9, 8, 9],
       [9, 4, 9, 1, 5],
       [5, 9, 8, 8, 2],
       [5, 6, 5, 4, 9]])

In [26]:
np.average(arr_1)

5.8

In [27]:
np.average(arr_1, axis = 0)

array([6.2, 5.2, 6.6, 5.2, 5.8])

In [28]:
x = np.average(arr_1, axis = 1)
x[0]

3.6

**sum**

In [30]:
arr_1

array([[4, 3, 2, 5, 4],
       [8, 4, 9, 8, 9],
       [9, 4, 9, 1, 5],
       [5, 9, 8, 8, 2],
       [5, 6, 5, 4, 9]])

In [31]:
np.sum(arr_1)

145

In [32]:
np.sum(arr_1, axis = 0)

array([31, 26, 33, 26, 29])

In [29]:
np.sum(arr_1, axis = 1)

array([18, 38, 28, 32, 29])

### 2.2) sqrt, exp, log, sin

**power**

In [33]:
arr_1

array([[4, 3, 2, 5, 4],
       [8, 4, 9, 8, 9],
       [9, 4, 9, 1, 5],
       [5, 9, 8, 8, 2],
       [5, 6, 5, 4, 9]])

In [34]:
np.sqrt(arr_1)

array([[2.        , 1.73205081, 1.41421356, 2.23606798, 2.        ],
       [2.82842712, 2.        , 3.        , 2.82842712, 3.        ],
       [3.        , 2.        , 3.        , 1.        , 2.23606798],
       [2.23606798, 3.        , 2.82842712, 2.82842712, 1.41421356],
       [2.23606798, 2.44948974, 2.23606798, 2.        , 3.        ]])

In [35]:
np.exp(arr_1)

array([[5.45981500e+01, 2.00855369e+01, 7.38905610e+00, 1.48413159e+02,
        5.45981500e+01],
       [2.98095799e+03, 5.45981500e+01, 8.10308393e+03, 2.98095799e+03,
        8.10308393e+03],
       [8.10308393e+03, 5.45981500e+01, 8.10308393e+03, 2.71828183e+00,
        1.48413159e+02],
       [1.48413159e+02, 8.10308393e+03, 2.98095799e+03, 2.98095799e+03,
        7.38905610e+00],
       [1.48413159e+02, 4.03428793e+02, 1.48413159e+02, 5.45981500e+01,
        8.10308393e+03]])

In [36]:
np.power(arr_1, 3)

array([[ 64,  27,   8, 125,  64],
       [512,  64, 729, 512, 729],
       [729,  64, 729,   1, 125],
       [125, 729, 512, 512,   8],
       [125, 216, 125,  64, 729]], dtype=int32)

In [37]:
arr_1*2

array([[ 8,  6,  4, 10,  8],
       [16,  8, 18, 16, 18],
       [18,  8, 18,  2, 10],
       [10, 18, 16, 16,  4],
       [10, 12, 10,  8, 18]])

In [38]:
np.log(arr_1)

array([[1.38629436, 1.09861229, 0.69314718, 1.60943791, 1.38629436],
       [2.07944154, 1.38629436, 2.19722458, 2.07944154, 2.19722458],
       [2.19722458, 1.38629436, 2.19722458, 0.        , 1.60943791],
       [1.60943791, 2.19722458, 2.07944154, 2.07944154, 0.69314718],
       [1.60943791, 1.79175947, 1.60943791, 1.38629436, 2.19722458]])

In [39]:
np.sin(arr_1)

array([[-0.7568025 ,  0.14112001,  0.90929743, -0.95892427, -0.7568025 ],
       [ 0.98935825, -0.7568025 ,  0.41211849,  0.98935825,  0.41211849],
       [ 0.41211849, -0.7568025 ,  0.41211849,  0.84147098, -0.95892427],
       [-0.95892427,  0.41211849,  0.98935825,  0.98935825,  0.90929743],
       [-0.95892427, -0.2794155 , -0.95892427, -0.7568025 ,  0.41211849]])

### 2.4) Matrix Multiplication

In [40]:
arr_3 = np.random.randint(1,10, (5,3))
arr_4 = np.random.randint(1,10, (3,6))


In [41]:
arr_3 @ arr_4

array([[ 41,  55,  29,  32,  83,  75],
       [111,  87, 110,  63, 163,  87],
       [ 89,  79,  81,  52, 139,  83],
       [ 71,  52,  76,  42, 102,  55],
       [ 50,  37,  39,  18,  67,  16]])

In [42]:
np.dot(arr_3, arr_4)

array([[ 41,  55,  29,  32,  83,  75],
       [111,  87, 110,  63, 163,  87],
       [ 89,  79,  81,  52, 139,  83],
       [ 71,  52,  76,  42, 102,  55],
       [ 50,  37,  39,  18,  67,  16]])

In [43]:
np.matmul(arr_3, arr_4)

array([[ 41,  55,  29,  32,  83,  75],
       [111,  87, 110,  63, 163,  87],
       [ 89,  79,  81,  52, 139,  83],
       [ 71,  52,  76,  42, 102,  55],
       [ 50,  37,  39,  18,  67,  16]])

# Great Job!

That's all we need to know for now!